//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourSolid.Cqrs.OrdiniClienti.Domain.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourSolid.Cqrs.OrdiniClienti.Domain.Rules.Resources.DomainExceptions", typeof(DomainExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articolo Non Trovato nel ReadModel!.
        /// </summary>
        public static string ArticoloIdNotFoundException {
            get {
                return ResourceManager.GetString("ArticoloIdNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArticoloId Obbligatorio!.
        /// </summary>
        public static string ArticoloIdNullException {
            get {
                return ResourceManager.GetString("ArticoloIdNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId Non Trovato nel ReadModel!.
        /// </summary>
        public static string ClienteIdNotFoundException {
            get {
                return ResourceManager.GetString("ClienteIdNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClienteId Obbligatorio!.
        /// </summary>
        public static string ClienteIdNullException {
            get {
                return ResourceManager.GetString("ClienteIdNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdineClienteId Obbligatorio!.
        /// </summary>
        public static string OrdineClienteIdNullException {
            get {
                return ResourceManager.GetString("OrdineClienteIdNullException", resourceCulture);
            }
        }
    }
}
